# Generated by Django 5.2.5 on 2026-07-29 13:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_reference', models.CharField(max_length=255)),
                ('recurrence_definition', models.JSONField()),
                ('timezone', models.CharField(max_length=64)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('ENDED', 'Ended'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scheduling_schedule_definition',
                'indexes': [models.Index(fields=['owner_reference'], name='sched_owner_ref_idx'), models.Index(fields=['status'], name='sched_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('scheduled_for', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('DUE', 'Due'), ('CANCELLED', 'Cancelled'), ('SKIPPED', 'Skipped')], default='SCHEDULED', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='scheduling.scheduledefinition')),
            ],
            options={
                'db_table': 'scheduling_occurrence',
                'indexes': [models.Index(fields=['schedule_definition', 'scheduled_for'], name='sched_occ_scheduled_idx'), models.Index(fields=['status', 'scheduled_for'], name='sched_occ_status_due_idx')],
                'constraints': [models.UniqueConstraint(fields=('schedule_definition', 'scheduled_for'), name='scheduling_occurrence_unique_slot')],
            },
        ),
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_time', models.DateTimeField()),
                ('replacement_time', models.DateTimeField(blank=True, null=True)),
                ('exception_type', models.CharField(choices=[('SKIP', 'Skip'), ('CANCEL', 'Cancel'), ('RESCHEDULE', 'Reschedule')], max_length=16)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('schedule_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='scheduling.scheduledefinition')),
            ],
            options={
                'db_table': 'scheduling_schedule_exception',
                'constraints': [models.UniqueConstraint(fields=('schedule_definition', 'original_time'), name='scheduling_exception_unique_slot')],
            },
        ),
    ]
