# Generated by Django 5.2.5 on 2026-08-01 07:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity_access', '0002_invitation_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('VOICE', 'Voice'), ('VIDEO', 'Video'), ('MESSAGE', 'Message')], max_length=16)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('CONNECTING', 'Connecting'), ('CONNECTED', 'Connected'), ('ENDED', 'Ended'), ('MISSED', 'Missed'), ('DECLINED', 'Declined'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='INITIATED', max_length=16)),
                ('outcome', models.CharField(blank=True, choices=[('ANSWERED', 'Answered'), ('MISSED', 'Missed'), ('DECLINED', 'Declined'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='', max_length=16)),
                ('initiated_at', models.DateTimeField()),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('external_execution_reference', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('elder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communication_sessions', to='identity_access.elder')),
            ],
            options={
                'db_table': 'communication_session',
            },
        ),
        migrations.CreateModel(
            name='CallAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField()),
                ('outcome', models.CharField(blank=True, default='', max_length=16)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=255)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('communication_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_attempts', to='communication.communicationsession')),
            ],
            options={
                'db_table': 'communication_call_attempt',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=128)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('communication_identities', models.JSONField(default=list)),
                ('preferred_channel', models.CharField(choices=[('VOICE', 'Voice'), ('VIDEO', 'Video'), ('MESSAGE', 'Message')], default='VOICE', max_length=16)),
                ('photo_reference', models.UUIDField(blank=True, null=True)),
                ('is_priority', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=16)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('elder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='identity_access.elder')),
            ],
            options={
                'db_table': 'communication_contact',
            },
        ),
        migrations.CreateModel(
            name='SessionParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('role', models.CharField(choices=[('INITIATOR', 'Initiator'), ('RECIPIENT', 'Recipient')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('communication_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='communication.communicationsession')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='session_participations', to='communication.contact')),
            ],
            options={
                'db_table': 'communication_session_participant',
            },
        ),
        migrations.AddIndex(
            model_name='communicationsession',
            index=models.Index(fields=['elder', 'initiated_at'], name='comm_session_elder_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationsession',
            index=models.Index(fields=['status'], name='comm_session_status_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationsession',
            index=models.Index(fields=['external_execution_reference'], name='comm_session_exec_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='callattempt',
            index=models.Index(fields=['communication_session', 'started_at'], name='comm_attempt_session_idx'),
        ),
        migrations.AddConstraint(
            model_name='callattempt',
            constraint=models.UniqueConstraint(fields=('communication_session', 'attempt_number'), name='comm_call_attempt_unique_number'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['elder', 'status'], name='comm_contact_elder_status_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['elder', 'is_priority'], name='comm_contact_priority_idx'),
        ),
        migrations.AddConstraint(
            model_name='sessionparticipant',
            constraint=models.UniqueConstraint(fields=('communication_session', 'role'), name='comm_session_participant_unique_role'),
        ),
    ]
