# Generated by Django 5.2.16 on 2026-09-05 09:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_communicationsession_aggregate_version'),
        ('identity_access', '0002_invitation_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=512)),
                ('file_size', models.PositiveBigIntegerField()),
                ('mime_type', models.CharField(max_length=128)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'communication_message_attachment',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_user_id', models.UUIDField(blank=True, null=True)),
                ('direction', models.CharField(choices=[('HUB_TO_FAMILY', 'Hub to Family'), ('FAMILY_TO_HUB', 'Family to Hub')], max_length=16)),
                ('message_type', models.CharField(choices=[('TEXT', 'Text'), ('VOICE', 'Voice'), ('IMAGE', 'Image'), ('VIDEO', 'Video')], max_length=16)),
                ('body', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed')], default='SENT', max_length=16)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('elder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='identity_access.elder')),
                ('sender_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='communication.contact')),
                ('attachment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message', to='communication.messageattachment')),
            ],
            options={
                'db_table': 'communication_message',
                'indexes': [models.Index(fields=['elder', '-created_at'], name='comm_msg_elder_created_idx'), models.Index(fields=['elder', 'status'], name='comm_msg_elder_status_idx'), models.Index(fields=['idempotency_key'], name='comm_msg_idempotency_idx')],
            },
        ),
    ]
