# Generated by Django 5.2.16 on 2026-09-05 12:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_messageattachment_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='delivered_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='read_at',
        ),
        migrations.CreateModel(
            name='MessageRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='communication.message')),
            ],
            options={
                'db_table': 'communication_message_recipient',
                'indexes': [models.Index(fields=['message', 'user_id'], name='comm_msg_recipient_idx'), models.Index(fields=['user_id', 'delivered_at'], name='comm_msg_recip_deliv_idx')],
                'constraints': [models.UniqueConstraint(fields=('message', 'user_id'), name='comm_message_recipient_unique_user')],
            },
        ),
    ]
