# Generated by Django 5.2.17 on 2026-08-15 21:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderRoomBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('elder_id', models.UUIDField()),
                ('provider', models.CharField(default='skyroom', max_length=32)),
                ('room_key', models.CharField(max_length=128)),
                ('external_room_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'infrastructure_provider_room_binding',
                'indexes': [models.Index(fields=['elder_id'], name='infra_provider_room_elder_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'elder_id'), name='infra_provider_room_elder_uniq')],
            },
        ),
        migrations.CreateModel(
            name='ProviderUserBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='skyroom', max_length=32)),
                ('subject_type', models.CharField(choices=[('USER', 'Family user'), ('ELDER_HUB', 'Elder Hub')], max_length=16)),
                ('subject_id', models.UUIDField()),
                ('user_key', models.CharField(max_length=128)),
                ('external_user_id', models.CharField(max_length=64)),
                ('display_name', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'infrastructure_provider_user_binding',
                'constraints': [models.UniqueConstraint(fields=('provider', 'subject_type', 'subject_id'), name='infra_provider_user_subject_uniq')],
            },
        ),
        migrations.CreateModel(
            name='ProviderCallBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('communication_session_id', models.UUIDField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room_binding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='call_bindings', to='infrastructure.providerroombinding')),
                ('user_binding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='call_bindings', to='infrastructure.provideruserbinding')),
            ],
            options={
                'db_table': 'infrastructure_provider_call_binding',
            },
        ),
    ]
