import uuid

# Stable namespace for deterministic occurrence and event identities.
SCHEDULING_NAMESPACE = uuid.UUID("6ba7b811-9dad-11d1-80b4-00c04fd430c8")

# Default batching window for occurrence generation when range_end is omitted.
# This does NOT end the schedule, modify end_at, or change recurrence semantics.
# Subsequent windows can be generated by calling generate_occurrences_for_schedule
# with later range_start/range_end values.
DEFAULT_GENERATION_HORIZON_DAYS = 90
