# Generated by Django 5.2.5 on 2026-08-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedIntegrationEvent',
            fields=[
                ('event_id', models.UUIDField(primary_key=True, serialize=False)),
                ('consumer', models.CharField(default='integration', max_length=64)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'integration_processed_event',
                'indexes': [models.Index(fields=['consumer', 'processed_at'], name='integration_evt_consumer_idx')],
            },
        ),
    ]
