# Generated by Django 5.2.5 on 2026-08-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0002_processed_event_handler_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedintegrationevent',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
