# Generated by Django 5.2.5 on 2026-08-01 07:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity_access', '0002_invitation_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=128, unique=True)),
                ('operational_status', models.CharField(choices=[('INVENTORY', 'Inventory'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('REVOKED', 'Revoked')], default='INVENTORY', max_length=16)),
                ('current_state', models.JSONField(default=dict)),
                ('configuration', models.JSONField(default=dict)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'device',
            },
        ),
        migrations.CreateModel(
            name='DeviceCapability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'device_capability',
            },
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=128)),
                ('model_code', models.CharField(max_length=64, unique=True)),
                ('model_name', models.CharField(max_length=128)),
                ('device_type', models.CharField(default='GENERIC', max_length=64)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'device_model',
            },
        ),
        migrations.CreateModel(
            name='Compartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=16)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartments', to='device.device')),
            ],
            options={
                'db_table': 'device_compartment',
            },
        ),
        migrations.CreateModel(
            name='DeviceAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment_type', models.CharField(choices=[('OWNED', 'Owned'), ('RENTED', 'Rented'), ('LOANER', 'Loaner')], max_length=16)),
                ('status', models.CharField(choices=[('INVENTORY', 'Inventory'), ('ASSIGNED', 'Assigned'), ('RETURNED', 'Returned'), ('REFURBISHED', 'Refurbished')], max_length=16)),
                ('assigned_at', models.DateTimeField()),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='device.device')),
                ('elder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_assignments', to='identity_access.elder')),
            ],
            options={
                'db_table': 'device_assignment',
            },
        ),
        migrations.CreateModel(
            name='DeviceCapabilityOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('ENABLED', 'Enabled'), ('DISABLED', 'Disabled')], max_length=16)),
                ('reason', models.TextField()),
                ('changed_by_user_id', models.UUIDField()),
                ('effective_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_overrides', to='device.devicecapability')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_overrides', to='device.device')),
            ],
            options={
                'db_table': 'device_capability_override',
            },
        ),
        migrations.CreateModel(
            name='DeviceCommand',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('command_type', models.CharField(choices=[('OPEN_COMPARTMENT', 'Open Compartment'), ('CLOSE_COMPARTMENT', 'Close Compartment'), ('PLAY_AUDIO', 'Play Audio'), ('SHOW_DISPLAY', 'Show Display'), ('DIAGNOSTIC', 'Diagnostic')], max_length=32)),
                ('parameters', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('DELIVERED', 'Delivered'), ('EXECUTING', 'Executing'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('result', models.JSONField(default=dict)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=255)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('execution_reference', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('executing_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('target_device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commands', to='device.device')),
            ],
            options={
                'db_table': 'device_command',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='device_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='device.devicemodel'),
        ),
        migrations.CreateModel(
            name='DeviceModelCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_capabilities', to='device.devicecapability')),
                ('device_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_capabilities', to='device.devicemodel')),
            ],
            options={
                'db_table': 'device_model_capability',
            },
        ),
        migrations.CreateModel(
            name='Pairing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PAIRING', 'Pairing'), ('ACTIVE', 'Active'), ('DISCONNECTED', 'Disconnected'), ('REVOKED', 'Revoked')], default='PAIRING', max_length=16)),
                ('paired_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hub_device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hub_pairings', to='device.device')),
                ('peripheral_device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='peripheral_pairings', to='device.device')),
            ],
            options={
                'db_table': 'device_pairing',
            },
        ),
        migrations.CreateModel(
            name='CompartmentAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('care_activity_reference', models.UUIDField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RELEASED', 'Released')], default='ACTIVE', max_length=16)),
                ('assigned_at', models.DateTimeField()),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compartment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='device.compartment')),
            ],
            options={
                'db_table': 'device_compartment_assignment',
                'indexes': [models.Index(fields=['compartment', 'status'], name='device_comp_assign_status_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='compartment',
            constraint=models.UniqueConstraint(fields=('device', 'number'), name='device_compartment_unique_number'),
        ),
        migrations.AddIndex(
            model_name='deviceassignment',
            index=models.Index(fields=['device', 'status'], name='device_assignment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceassignment',
            index=models.Index(fields=['elder', 'status'], name='device_assignment_elder_idx'),
        ),
        migrations.AddIndex(
            model_name='devicecapabilityoverride',
            index=models.Index(fields=['device', 'capability', 'effective_at'], name='device_cap_override_idx'),
        ),
        migrations.AddIndex(
            model_name='devicecommand',
            index=models.Index(fields=['target_device', 'status'], name='device_command_status_idx'),
        ),
        migrations.AddIndex(
            model_name='devicecommand',
            index=models.Index(fields=['execution_reference'], name='device_command_exec_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['operational_status'], name='device_operational_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='devicemodelcapability',
            constraint=models.UniqueConstraint(fields=('device_model', 'capability'), name='device_model_capability_unique'),
        ),
        migrations.AddIndex(
            model_name='pairing',
            index=models.Index(fields=['hub_device', 'status'], name='device_pairing_hub_idx'),
        ),
    ]
