"""Occurrence generation and queries."""

from __future__ import annotations

import uuid
from datetime import datetime, timedelta

from django.db import IntegrityError, transaction
from django.utils import timezone
from zoneinfo import ZoneInfo

from domains.scheduling.constants import DEFAULT_GENERATION_HORIZON_DAYS
from domains.scheduling.enums import OccurrenceStatus, ScheduleExceptionType, ScheduleStatus
from domains.scheduling.exceptions import (
    InvalidOccurrenceStateError,
    OccurrenceNotFoundError,
    RescheduleCollisionError,
    ScheduleNotFoundError,
)
from domains.scheduling.identity import compute_occurrence_id, normalize_instant
from domains.scheduling.models import Occurrence, ScheduleDefinition, ScheduleException
from domains.scheduling.recurrence.engine import iter_recurrence_slots
from domains.scheduling.services.events import (
    emit_occurrence_cancelled,
    emit_occurrence_scheduled,
    emit_occurrence_skipped,
)


def get_occurrence(occurrence_id: uuid.UUID) -> Occurrence:
    try:
        return Occurrence.objects.select_related("schedule_definition").get(pk=occurrence_id)
    except Occurrence.DoesNotExist as exc:
        raise OccurrenceNotFoundError("Occurrence not found.") from exc


def get_next_occurrence(*, schedule_definition_id: uuid.UUID, after: datetime | None = None) -> Occurrence | None:
    after = after or timezone.now()
    return (
        Occurrence.objects.filter(
            schedule_definition_id=schedule_definition_id,
            scheduled_for__gt=after,
            status=OccurrenceStatus.SCHEDULED,
        )
        .order_by("scheduled_for")
        .first()
    )


def get_upcoming_occurrences(
    *,
    schedule_definition_id: uuid.UUID,
    limit: int = 10,
    after: datetime | None = None,
) -> list[Occurrence]:
    after = after or timezone.now()
    return list(
        Occurrence.objects.filter(
            schedule_definition_id=schedule_definition_id,
            scheduled_for__gt=after,
        )
        .order_by("scheduled_for")[:limit]
    )


def get_occurrences_between(
    *,
    schedule_definition_id: uuid.UUID,
    start: datetime,
    end: datetime,
) -> list[Occurrence]:
    return list(
        Occurrence.objects.filter(
            schedule_definition_id=schedule_definition_id,
            scheduled_for__gte=start,
            scheduled_for__lte=end,
        ).order_by("scheduled_for")
    )


def assert_reschedule_does_not_collide(
    *,
    schedule_definition_id: uuid.UUID,
    replacement_time: datetime,
    occurrence_id: uuid.UUID,
) -> None:
    """Reject reschedules that would occupy another occurrence's scheduled_for."""
    normalized = normalize_instant(replacement_time)
    collision = (
        Occurrence.objects.filter(
            schedule_definition_id=schedule_definition_id,
            scheduled_for=normalized,
        )
        .exclude(pk=occurrence_id)
        .exists()
    )
    if collision:
        raise RescheduleCollisionError(
            "Reschedule replacement_time conflicts with an existing occurrence."
        )


def _exception_map(schedule: ScheduleDefinition) -> dict[datetime, ScheduleException]:
    mapping: dict[datetime, ScheduleException] = {}
    for exc in schedule.exceptions.all():
        mapping[normalize_instant(exc.original_time)] = exc
    return mapping


def _resolve_slot(
  *,
  schedule: ScheduleDefinition,
  original_time: datetime,
  exceptions: dict[datetime, ScheduleException],
) -> tuple[datetime, OccurrenceStatus] | None:
    original_time = normalize_instant(original_time)
    exception = exceptions.get(original_time)
    if exception is None:
        return original_time, OccurrenceStatus.SCHEDULED
    if exception.exception_type == ScheduleExceptionType.SKIP:
        return original_time, OccurrenceStatus.SKIPPED
    if exception.exception_type == ScheduleExceptionType.CANCEL:
        return original_time, OccurrenceStatus.CANCELLED
    if exception.exception_type == ScheduleExceptionType.RESCHEDULE:
        if exception.replacement_time is None:
            return original_time, OccurrenceStatus.SCHEDULED
        return normalize_instant(exception.replacement_time), OccurrenceStatus.SCHEDULED
    return original_time, OccurrenceStatus.SCHEDULED


@transaction.atomic
def generate_occurrences_for_schedule(
    schedule: ScheduleDefinition,
    *,
    range_start: datetime | None = None,
    range_end: datetime | None = None,
    emit_events: bool = True,
) -> list[Occurrence]:
    """Generate occurrences for an explicit window.

    When ``range_end`` is omitted, ``DEFAULT_GENERATION_HORIZON_DAYS`` is used as
    a batching default only. It does not end the schedule, modify ``end_at``, or
    change recurrence semantics. Later windows can be generated by calling this
    function again with subsequent ``range_start`` / ``range_end`` values.
    """
    schedule.refresh_from_db()
    if schedule.status != ScheduleStatus.ACTIVE:
        return []

    now = timezone.now()
    range_start = range_start or now
    range_end = range_end or (now + timedelta(days=DEFAULT_GENERATION_HORIZON_DAYS))
    exceptions = _exception_map(schedule)
    created: list[Occurrence] = []

    for slot in iter_recurrence_slots(
        recurrence_definition=schedule.recurrence_definition,
        timezone_name=schedule.timezone,
        start_at=schedule.start_at,
        end_at=schedule.end_at,
        range_start=range_start,
        range_end=range_end,
    ):
        resolved = _resolve_slot(
            schedule=schedule,
            original_time=slot.original_time,
            exceptions=exceptions,
        )
        if resolved is None:
            continue
        scheduled_for, status = resolved
        occurrence_id = compute_occurrence_id(
            schedule_definition_id=schedule.id,
            original_time=slot.original_time,
        )
        if scheduled_for != normalize_instant(slot.original_time):
            assert_reschedule_does_not_collide(
                schedule_definition_id=schedule.id,
                replacement_time=scheduled_for,
                occurrence_id=occurrence_id,
            )
        occurrence, was_created = _get_or_create_occurrence(
            occurrence_id=occurrence_id,
            schedule=schedule,
            scheduled_for=scheduled_for,
            status=status,
        )
        if was_created:
            created.append(occurrence)
            if emit_events and status == OccurrenceStatus.SCHEDULED:
                emit_occurrence_scheduled(
                    occurrence_id=occurrence.id,
                    schedule_definition_id=schedule.id,
                    scheduled_for=occurrence.scheduled_for,
                )
    return created


def _get_or_create_occurrence(
    *,
    occurrence_id: uuid.UUID,
    schedule: ScheduleDefinition,
    scheduled_for: datetime,
    status: OccurrenceStatus,
) -> tuple[Occurrence, bool]:
    existing = Occurrence.objects.filter(pk=occurrence_id).first()
    if existing is not None:
        return existing, False
    try:
        occurrence = Occurrence.objects.create(
            id=occurrence_id,
            schedule_definition=schedule,
            scheduled_for=scheduled_for,
            status=status,
        )
        return occurrence, True
    except IntegrityError as exc:
        existing = Occurrence.objects.filter(pk=occurrence_id).first()
        if existing is not None:
            return existing, False
        raise RescheduleCollisionError(
            "Reschedule replacement_time conflicts with an existing occurrence."
        ) from exc


@transaction.atomic
def skip_occurrence(*, occurrence_id: uuid.UUID) -> Occurrence:
    occurrence = get_occurrence(occurrence_id)
    if occurrence.status == OccurrenceStatus.SKIPPED:
        return occurrence
    if occurrence.status not in {OccurrenceStatus.SCHEDULED, OccurrenceStatus.DUE}:
        raise InvalidOccurrenceStateError("Only scheduled or due occurrences can be skipped.")
    occurrence.status = OccurrenceStatus.SKIPPED
    occurrence.save(update_fields=["status"])
    emit_occurrence_skipped(
        occurrence_id=occurrence.id,
        schedule_definition_id=occurrence.schedule_definition_id,
        scheduled_for=occurrence.scheduled_for,
    )
    return occurrence


@transaction.atomic
def cancel_occurrence(*, occurrence_id: uuid.UUID) -> Occurrence:
    occurrence = get_occurrence(occurrence_id)
    if occurrence.status != OccurrenceStatus.SCHEDULED:
        raise InvalidOccurrenceStateError("Only scheduled occurrences can be cancelled.")
    occurrence.status = OccurrenceStatus.CANCELLED
    occurrence.save(update_fields=["status"])
    emit_occurrence_cancelled(
        occurrence_id=occurrence.id,
        schedule_definition_id=occurrence.schedule_definition_id,
        scheduled_for=occurrence.scheduled_for,
    )
    return occurrence


def ensure_schedule_exists(schedule_definition_id: uuid.UUID) -> ScheduleDefinition:
    try:
        return ScheduleDefinition.objects.get(pk=schedule_definition_id)
    except ScheduleDefinition.DoesNotExist as exc:
        raise ScheduleNotFoundError("Schedule not found.") from exc
