# Generated by Django 5.2.5 on 2026-08-01 08:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReplicaState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('replica_identifier', models.UUIDField(unique=True)),
                ('replica_type', models.CharField(choices=[('BACKEND', 'Backend'), ('HUB', 'Hub')], max_length=16)),
                ('health', models.CharField(choices=[('HEALTHY', 'Healthy'), ('OUTDATED', 'Outdated'), ('UNAVAILABLE', 'Unavailable')], default='HEALTHY', max_length=16)),
                ('status', models.CharField(choices=[('IDLE', 'Idle'), ('SYNCHRONIZING', 'Synchronizing'), ('RESETTING', 'Resetting'), ('OUTDATED', 'Outdated'), ('UNAVAILABLE', 'Unavailable')], default='IDLE', max_length=16)),
                ('checkpoint_sequence', models.PositiveBigIntegerField(default=0)),
                ('checkpoint_token', models.UUIDField(blank=True, null=True)),
                ('last_successful_sync', models.DateTimeField(blank=True, null=True)),
                ('statistics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'synchronization_replica_state',
                'indexes': [models.Index(fields=['replica_identifier'], name='sync_replica_identifier_idx'), models.Index(fields=['status'], name='sync_replica_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='SynchronizationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('UPLOAD', 'Upload'), ('DOWNLOAD', 'Download')], max_length=16)),
                ('status', models.CharField(choices=[('SYNCHRONIZATION_REQUESTED', 'Synchronization Requested'), ('SESSION_STARTED', 'Session Started'), ('PAYLOAD_RECEIVED', 'Payload Received'), ('VALIDATION', 'Validation'), ('CHANGES_APPLIED', 'Changes Applied'), ('CHECKPOINT_ADVANCED', 'Checkpoint Advanced'), ('SESSION_COMPLETED', 'Session Completed'), ('TRANSFER_FAILED', 'Transfer Failed'), ('RETRY_SCHEDULED', 'Retry Scheduled'), ('SYNCHRONIZATION_RESUMED', 'Synchronization Resumed'), ('CANCELLED', 'Cancelled')], default='SYNCHRONIZATION_REQUESTED', max_length=32)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('statistics', models.JSONField(default=dict)),
                ('synchronization_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('replica_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='synchronization.replicastate')),
            ],
            options={
                'db_table': 'synchronization_session',
            },
        ),
        migrations.CreateModel(
            name='SynchronizationOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('DELTA', 'Delta'), ('SNAPSHOT', 'Snapshot')], max_length=16)),
                ('aggregate_reference', models.UUIDField()),
                ('aggregate_version', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('payload_type', models.CharField(max_length=64)),
                ('payload_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VALIDATED', 'Validated'), ('APPLIED', 'Applied'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=255)),
                ('started_at', models.DateTimeField()),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synchronization_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='synchronization.synchronizationsession')),
            ],
            options={
                'db_table': 'synchronization_operation',
            },
        ),
        migrations.CreateModel(
            name='SynchronizationConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aggregate_reference', models.UUIDField()),
                ('conflict_type', models.CharField(choices=[('CONCURRENT_CHANGE', 'Concurrent Change'), ('CHECKPOINT_MISMATCH', 'Checkpoint Mismatch'), ('VERSION_MISMATCH', 'Version Mismatch')], max_length=32)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=16)),
                ('local_version', models.CharField(blank=True, default='', max_length=64)),
                ('remote_version', models.CharField(blank=True, default='', max_length=64)),
                ('resolution_payload', models.JSONField(blank=True, null=True)),
                ('detected_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replica_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='synchronization.replicastate')),
                ('synchronization_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflicts', to='synchronization.synchronizationsession')),
            ],
            options={
                'db_table': 'synchronization_conflict',
            },
        ),
        migrations.CreateModel(
            name='ReplicaVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aggregate_reference', models.UUIDField()),
                ('aggregate_version', models.CharField(max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replica_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregate_versions', to='synchronization.replicastate')),
            ],
            options={
                'db_table': 'synchronization_replica_version',
                'constraints': [models.UniqueConstraint(fields=('replica_state', 'aggregate_reference'), name='sync_replica_version_unique_aggregate')],
            },
        ),
        migrations.AddIndex(
            model_name='synchronizationsession',
            index=models.Index(fields=['replica_state', 'started_at'], name='sync_session_replica_idx'),
        ),
        migrations.AddIndex(
            model_name='synchronizationsession',
            index=models.Index(fields=['status'], name='sync_session_status_idx'),
        ),
        migrations.AddIndex(
            model_name='synchronizationsession',
            index=models.Index(fields=['synchronization_token'], name='sync_session_token_idx'),
        ),
        migrations.AddIndex(
            model_name='synchronizationoperation',
            index=models.Index(fields=['synchronization_session', 'started_at'], name='sync_op_session_idx'),
        ),
        migrations.AddIndex(
            model_name='synchronizationoperation',
            index=models.Index(fields=['aggregate_reference'], name='sync_op_aggregate_idx'),
        ),
        migrations.AddIndex(
            model_name='synchronizationconflict',
            index=models.Index(fields=['replica_state', 'status'], name='sync_conflict_replica_idx'),
        ),
        migrations.AddIndex(
            model_name='synchronizationconflict',
            index=models.Index(fields=['aggregate_reference'], name='sync_conflict_aggregate_idx'),
        ),
    ]
