# Generated by Django 5.2.5 on 2026-09-08 07:15

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('elder_id', models.UUIDField(db_index=True)),
                ('payer_user_id', models.UUIDField(db_index=True)),
                ('subscription_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=14)),
                ('currency', models.CharField(choices=[('TOMAN', 'Toman'), ('IRR', 'Iranian Rial'), ('USD', 'US Dollar')], default='TOMAN', max_length=16)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('VOID', 'Void'), ('REFUNDED', 'Refunded')], default='UNPAID', max_length=16)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'billing_invoice',
                'constraints': [models.CheckConstraint(condition=models.Q(('total_amount__gte', Decimal('0'))), name='billing_invoice_total_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('line_type', models.CharField(default='SUBSCRIPTION', max_length=32)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='billing.invoice')),
            ],
            options={
                'db_table': 'billing_invoice_line_item',
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('FAKE', 'Fake'), ('ZARINPAL', 'ZarinPal'), ('STRIPE', 'Stripe')], default='FAKE', max_length=32)),
                ('provider_reference', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('idempotency_key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('REDIRECTED', 'Redirected'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='INITIATED', max_length=16)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='billing.invoice')),
            ],
            options={
                'db_table': 'billing_payment_attempt',
            },
        ),
        migrations.CreateModel(
            name='PlanPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_code', models.CharField(db_index=True, max_length=64)),
                ('interval', models.CharField(choices=[('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual')], default='MONTHLY', max_length=16)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14)),
                ('currency', models.CharField(choices=[('TOMAN', 'Toman'), ('IRR', 'Iranian Rial'), ('USD', 'US Dollar')], default='TOMAN', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'billing_plan_price',
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0'))), name='billing_plan_price_non_negative'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('plan_code', 'interval', 'currency'), name='billing_plan_price_single_active_per_tier')],
            },
        ),
    ]
