# Generated by Django 5.2.16 on 2026-07-29 12:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity_access', '0002_invitation_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('kind', models.CharField(choices=[('FEATURE', 'Feature'), ('LIMIT', 'Limit')], max_length=16)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'licensing_entitlement',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'licensing_plan',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=16)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('elder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='identity_access.elder')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='licensing.plan')),
            ],
            options={
                'db_table': 'licensing_license',
            },
        ),
        migrations.CreateModel(
            name='LicensePlanHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_history', to='licensing.license')),
                ('new_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='new_license_plans', to='licensing.plan')),
                ('previous_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='previous_license_plans', to='licensing.plan')),
            ],
            options={
                'db_table': 'licensing_license_plan_history',
            },
        ),
        migrations.CreateModel(
            name='PlanEntitlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=64)),
                ('entitlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_entitlements', to='licensing.entitlement')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_entitlements', to='licensing.plan')),
            ],
            options={
                'db_table': 'licensing_plan_entitlement',
            },
        ),
        migrations.AddConstraint(
            model_name='license',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_until__gte', models.F('valid_from')), _connector='OR'), name='licensing_license_valid_window'),
        ),
        migrations.AddConstraint(
            model_name='planentitlement',
            constraint=models.UniqueConstraint(fields=('plan', 'entitlement'), name='licensing_plan_entitlement_unique'),
        ),
    ]
