# Generated by Django 5.2.5 on 2026-09-08 06:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity_access', '0003_seed_baseline_roles_permissions'),
        ('licensing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past Due'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING_PAYMENT', max_length=16)),
                ('started_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('auto_renew', models.BooleanField(default=False)),
                ('is_trial', models.BooleanField(default=False)),
                ('payer_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'licensing_subscription',
            },
        ),
        migrations.AddConstraint(
            model_name='license',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('elder',), name='licensing_license_single_active_per_elder'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='licensing.license'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='licensing.plan'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('started_at'))), name='licensing_subscription_valid_window'),
        ),
    ]
