# Generated by Django 5.2.5 on 2026-07-29 13:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=128)),
                ('event_version', models.PositiveIntegerField()),
                ('producer', models.CharField(max_length=128)),
                ('occurred_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=128)),
                ('causation_id', models.CharField(blank=True, default='', max_length=128)),
                ('elder_id', models.UUIDField(blank=True, null=True)),
                ('payload', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'event_record',
                'indexes': [models.Index(fields=['correlation_id'], name='event_record_correlation_idx'), models.Index(fields=['producer'], name='event_record_producer_idx'), models.Index(fields=['occurred_at'], name='event_record_occurred_idx'), models.Index(fields=['elder_id'], name='event_record_elder_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PUBLISHED', 'Published')], default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outbox_entry', to='event.eventrecord')),
            ],
            options={
                'db_table': 'event_outbox',
                'indexes': [models.Index(fields=['status', 'created_at'], name='event_outbox_status_idx')],
            },
        ),
    ]
