# Generated by Django 5.2.5 on 2026-07-29 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='eventrecord',
            name='event_record_elder_idx',
        ),
        migrations.RemoveField(
            model_name='eventrecord',
            name='elder_id',
        ),
    ]
