# Generated by Django 5.2.5 on 2026-08-01 06:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity_access', '0002_invitation_role'),
        ('scheduling', '0001_initial'),
        ('workflow', '0002_alter_confirmationevidence_evidence_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('MEDICATION', 'Medication'), ('EXERCISE', 'Exercise'), ('DAILY_CHECK_IN', 'Daily Check-in'), ('GENERAL', 'General')], max_length=32)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('ENDED', 'Ended'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=16)),
                ('display_title', models.CharField(max_length=128)),
                ('display_subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('display_icon', models.CharField(blank=True, default='', max_length=64)),
                ('confirmation_requirement', models.JSONField(default=dict)),
                ('compartment_assignment_reference', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('elder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='care_activities', to='identity_access.elder')),
                ('schedule_definition', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='care_activity', to='scheduling.scheduledefinition')),
                ('workflow_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='care_activities', to='workflow.workflowdefinition')),
            ],
            options={
                'db_table': 'care_activity',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('care_activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='prescription', serialize=False, to='care.careactivity')),
                ('medication_reference', models.CharField(max_length=128)),
                ('dosage_information', models.CharField(max_length=255)),
                ('elder_friendly_description', models.TextField()),
                ('personalized_description', models.TextField(blank=True, default='')),
                ('media_reference', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'care_prescription',
            },
        ),
        migrations.CreateModel(
            name='CareCompletion',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('occurrence_id', models.UUIDField()),
                ('workflow_execution_id', models.UUIDField(unique=True)),
                ('completion_state', models.CharField(choices=[('MEDICATION_TAKEN', 'Medication Taken'), ('MEDICATION_MISSED', 'Medication Missed'), ('CARE_ACTIVITY_COMPLETED', 'Care Activity Completed'), ('CARE_ACTIVITY_MISSED', 'Care Activity Missed'), ('CARE_ACTIVITY_CANCELLED', 'Care Activity Cancelled'), ('CARE_ACTIVITY_FAILED', 'Care Activity Failed')], max_length=32)),
                ('interpreted_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('care_activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completions', to='care.careactivity')),
            ],
            options={
                'db_table': 'care_completion',
            },
        ),
        migrations.AddIndex(
            model_name='careactivity',
            index=models.Index(fields=['elder', 'status'], name='care_activity_elder_status_idx'),
        ),
        migrations.AddIndex(
            model_name='carecompletion',
            index=models.Index(fields=['care_activity', 'interpreted_at'], name='care_completion_history_idx'),
        ),
    ]
