# Generated by Django 5.2.5 on 2026-08-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='careactivity',
            name='aggregate_version',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
