# Generated by Django 5.2.5 on 2026-07-30 11:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=16)),
                ('definition', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workflow_definition',
            },
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('CONFIRMED', 'Confirmed'), ('MISSED', 'Missed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('current_step', models.CharField(default='initial', max_length=64)),
                ('postpone_count', models.PositiveIntegerField(default=0)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('escalation_index', models.PositiveIntegerField(default=0)),
                ('current_action', models.JSONField(default=dict)),
                ('active_until', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occurrence', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_execution', to='scheduling.occurrence')),
                ('workflow_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='workflow.workflowdefinition')),
            ],
            options={
                'db_table': 'workflow_execution',
            },
        ),
        migrations.CreateModel(
            name='ConfirmationEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(choices=[('HUB_CONFIRMATION', 'Hub Confirmation'), ('COMPARTMENT_CLOSED', 'Compartment Closed'), ('COMMUNICATION_SESSION_ENDED', 'Communication Session Ended')], max_length=64)),
                ('source_type', models.CharField(choices=[('DOMAIN_EVENT', 'Domain Event'), ('DIRECT_INTERACTION', 'Direct Interaction')], max_length=32)),
                ('source_reference', models.CharField(max_length=255)),
                ('actor_user_id', models.UUIDField(blank=True, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('workflow_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_records', to='workflow.workflowexecution')),
            ],
            options={
                'db_table': 'workflow_confirmation_evidence',
            },
        ),
        migrations.CreateModel(
            name='ActionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_reference', models.CharField(max_length=128)),
                ('action_type', models.CharField(max_length=64)),
                ('result_status', models.CharField(choices=[('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], max_length=16)),
                ('payload', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('workflow_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_results', to='workflow.workflowexecution')),
            ],
            options={
                'db_table': 'workflow_action_result',
            },
        ),
        migrations.CreateModel(
            name='WorkflowScheduleBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schedule_definition_id', models.UUIDField(unique=True)),
                ('workflow_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_bindings', to='workflow.workflowdefinition')),
            ],
            options={
                'db_table': 'workflow_schedule_binding',
            },
        ),
        migrations.AddIndex(
            model_name='workflowexecution',
            index=models.Index(fields=['status', 'active_until'], name='wf_exec_timeout_idx'),
        ),
        migrations.AddConstraint(
            model_name='confirmationevidence',
            constraint=models.UniqueConstraint(fields=('workflow_execution', 'source_type', 'source_reference'), name='workflow_evidence_idempotent'),
        ),
        migrations.AddConstraint(
            model_name='actionresult',
            constraint=models.UniqueConstraint(fields=('workflow_execution', 'action_reference'), name='workflow_action_result_idempotent'),
        ),
    ]
