# Generated by Django 5.2.5 on 2026-07-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationevidence',
            name='evidence_type',
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name='WorkflowScheduleBinding',
        ),
    ]
