# Generated by Django 5.2.5 on 2026-08-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_alter_confirmationevidence_evidence_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowexecution',
            name='aggregate_version',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
